[package]
name = "streamingpattern"
version = "0.1.0"
authors = ["Tommaso Checchi <tommaso.checchi1@gmail.com>"]

[dependencies]
piston = "0.27.0"
piston2d-graphics = "0.19.0"
piston2d-opengl_graphics = "0.37.0"
piston_window = "0.61.0"
image = "0.12.1"